//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public System.Guid AccountID { get; set; }
        public System.Guid PersonID { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public System.DateTime RegestrationDate { get; set; }
        public string Salt { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
