//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BakeryEntitiesHome : DbContext
    {
        public BakeryEntitiesHome()
            : base("name=BakeryEntitiesHome")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cклады> Cклады { get; set; }
        public virtual DbSet<Аккаунты> Аккаунты { get; set; }
        public virtual DbSet<Аккаунты___Роли> Аккаунты___Роли { get; set; }
        public virtual DbSet<Личности> Личности { get; set; }
        public virtual DbSet<Пекарни> Пекарни { get; set; }
        public virtual DbSet<Покупатели> Покупатели { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<Рецепты> Рецепты { get; set; }
        public virtual DbSet<Роли_пользователей> Роли_пользователей { get; set; }
        public virtual DbSet<Состав_рецепта> Состав_рецепта { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Сырье> Сырье { get; set; }
        public virtual DbSet<Справочник_должностей> Справочник_должностей { get; set; }
        public virtual DbSet<Справочник_типов_операций> Справочник_типов_операций { get; set; }
        public virtual DbSet<Справочник_типов_продукции> Справочник_типов_продукции { get; set; }
        public virtual DbSet<Справочник_типов_сырья> Справочник_типов_сырья { get; set; }
        public virtual DbSet<Журнал_учета_продукции> Журнал_учета_продукции { get; set; }
        public virtual DbSet<Журнал_учета_сырья> Журнал_учета_сырья { get; set; }
        public virtual DbSet<Остатки_продукции_на_складе> Остатки_продукции_на_складе { get; set; }
        public virtual DbSet<Остатки_сырья_на_складе> Остатки_сырья_на_складе { get; set; }
        public virtual DbSet<Состав_операций_по_продукции> Состав_операций_по_продукции { get; set; }
    }
}
