//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bakery
    {
        public Bakery()
        {
            this.Stock = new HashSet<Stock>();
            this.Employee = new HashSet<Employee>();
        }
    
        public System.Guid BakeryID { get; set; }
        public string Name { get; set; }
        public string FullAddress { get; set; }
    
        public virtual ICollection<Stock> Stock { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
