//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.ProductAccountingLog = new HashSet<ProductAccountingLog>();
        }
    
        public System.Guid CustomerID { get; set; }
        public System.Guid PersonID { get; set; }
        public int Balance { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<ProductAccountingLog> ProductAccountingLog { get; set; }
    }
}
