//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cклады
    {
        public Cклады()
        {
            this.Журнал_учета_продукции = new HashSet<Журнал_учета_продукции>();
            this.Журнал_учета_сырья = new HashSet<Журнал_учета_сырья>();
            this.Остатки_продукции_на_складе = new HashSet<Остатки_продукции_на_складе>();
            this.Остатки_сырья_на_складе = new HashSet<Остатки_сырья_на_складе>();
        }
    
        public System.Guid ID_Склада { get; set; }
        public string Тип_склада { get; set; }
        public string Адрес { get; set; }
        public Nullable<System.Guid> ID_Пекарни { get; set; }
    
        public virtual ICollection<Журнал_учета_продукции> Журнал_учета_продукции { get; set; }
        public virtual ICollection<Журнал_учета_сырья> Журнал_учета_сырья { get; set; }
        public virtual ICollection<Остатки_продукции_на_складе> Остатки_продукции_на_складе { get; set; }
        public virtual ICollection<Остатки_сырья_на_складе> Остатки_сырья_на_складе { get; set; }
        public virtual Пекарни Пекарни { get; set; }
    }
}
