//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailRawOperation
    {
        public System.Guid RecordID { get; set; }
        public System.Guid RawLogRecordID { get; set; }
        public System.Guid RawID { get; set; }
        public int Count { get; set; }
    
        public virtual Raw Raw { get; set; }
        public virtual RawAccountingLog RawAccountingLog { get; set; }
    }
}
