//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ProductAccuntingLog = new HashSet<ProductAccountingLog>();
            this.RawAccountingLog = new HashSet<RawAccountingLog>();
        }
    
        public System.Guid EmployeeID { get; set; }
        public System.Guid PersonID { get; set; }
        public System.Guid PositionID { get; set; }
        public Nullable<System.Guid> BakeryID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> DismissalDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Bakery Bakery { get; set; }
        public virtual ICollection<ProductAccountingLog> ProductAccuntingLog { get; set; }
        public virtual ICollection<RawAccountingLog> RawAccountingLog { get; set; }
        public virtual Position Position { get; set; }
    }
}
