//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingridient
    {
        public System.Guid IngridientID { get; set; }
        public System.Guid RecipeID { get; set; }
        public System.Guid RawTypeID { get; set; }
        public string Units { get; set; }
        public int Count { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual RawType RawType { get; set; }
    }
}
