//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationType
    {
        public OperationType()
        {
            this.ProductAccountingLog = new HashSet<ProductAccountingLog>();
            this.RawAccountingLog = new HashSet<RawAccountingLog>();
        }
    
        public System.Guid OperationTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<ProductAccountingLog> ProductAccountingLog { get; set; }
        public virtual ICollection<RawAccountingLog> RawAccountingLog { get; set; }
    }
}
