//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Customer = new HashSet<Customer>();
            this.Supplier = new HashSet<Supplier>();
            this.Employee = new HashSet<Employee>();
        }
    
        public System.Guid PersonID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
