//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public System.Guid PositionID { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public int CountWorkplases { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
