//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductResidue = new HashSet<ProductResidue>();
            this.Recipe = new HashSet<Recipe>();
            this.DetailProductOperation = new HashSet<DetailProductOperation>();
        }
    
        public System.Guid ProductID { get; set; }
        public System.Guid ProductTypeID { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Units { get; set; }
        public byte[] Image { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ProductResidue> ProductResidue { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<Recipe> Recipe { get; set; }
        public virtual ICollection<DetailProductOperation> DetailProductOperation { get; set; }
    }
}
