//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductResidue
    {
        public System.Guid ProductResidueID { get; set; }
        public System.Guid StockID { get; set; }
        public System.Guid ProductID { get; set; }
        public int Count { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Product Product { get; set; }
    }
}
