//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAccountingLog
    {
        public ProductAccountingLog()
        {
            this.DetailProductOperation = new HashSet<DetailProductOperation>();
        }
    
        public System.Guid LogRecordID { get; set; }
        public System.Guid OperationTypeID { get; set; }
        public System.Guid StockID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public System.DateTime OperationDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OperationType OperationType { get; set; }
        public virtual ICollection<DetailProductOperation> DetailProductOperation { get; set; }
    }
}
