//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace JustBakery.Models
{
  using System;
  using System.Collections.Generic;

  public partial class Raw
  {
    public Raw()
    {
      this.RawResidue = new HashSet<RawResidue>();
      this.DetailRawOperation = new HashSet<DetailRawOperation>();
    }

    public System.Guid RawID { get; set; }
    [Display(Name = "Тип сырья")]
    public System.Guid RawTypeID { get; set; }
    [Display(Name = "Цена")]
    public Nullable<int> Cost { get; set; }
    [Display(Name = "Единицы измерения")]
    public string Units { get; set; }
    [Display(Name = "Название")]
    public string Name { get; set; }

    public virtual ICollection<RawResidue> RawResidue { get; set; }
    public virtual RawType RawType { get; set; }
    public virtual ICollection<DetailRawOperation> DetailRawOperation { get; set; }
  }
}
