//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawType
    {
        public RawType()
        {
            this.RecipeComposition = new HashSet<RecipeComposition>();
            this.Raw = new HashSet<Raw>();
        }
    
        public System.Guid RawTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<RecipeComposition> RecipeComposition { get; set; }
        public virtual ICollection<Raw> Raw { get; set; }
    }
}
