//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace JustBakery.Models
{
  using System;
  using System.Collections.Generic;

  public partial class Recipe
  {
    public Recipe()
    {
      this.Ingridients = new HashSet<Ingridient>();
    }

    public System.Guid RecipeID { get; set; }
    [Display(Name = "Продукт")]
    public System.Guid ProductID { get; set; }
    [Display(Name = "Название")]
    public string Name { get; set; }
    [Display(Name = "Описание")]
    public string Description { get; set; }

    public virtual Product Product { get; set; }
    public virtual ICollection<Ingridient> Ingridients { get; set; }
  }
}
