//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.RecipeComposition = new HashSet<RecipeComposition>();
        }
    
        public System.Guid RecipeID { get; set; }
        public System.Guid ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<RecipeComposition> RecipeComposition { get; set; }
    }
}
