//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.RawAccountingLog = new HashSet<RawAccountingLog>();
        }
    
        public System.Guid SupplierID { get; set; }
        public Nullable<System.Guid> ContactPersonID { get; set; }
        public string INN { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string OfficePhone { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<RawAccountingLog> RawAccountingLog { get; set; }
    }
}
