//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аккаунты
    {
        public System.Guid ID_Аккаунта { get; set; }
        public System.Guid ID_Личности { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public System.DateTime Дата_регистрации { get; set; }
        public string Соль { get; set; }
    
        public virtual Личности Личности { get; set; }
    }
}
