//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Остатки_продукции_на_складе
    {
        public System.Guid ID_Остатка_продукции { get; set; }
        public System.Guid ID_Склада { get; set; }
        public System.Guid ID_Продукции { get; set; }
        public int Количество { get; set; }
    
        public virtual Cклады Cклады { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
