//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пекарни
    {
        public Пекарни()
        {
            this.Cклады = new HashSet<Cклады>();
            this.Сотрудники = new HashSet<Сотрудники>();
        }
    
        public System.Guid ID_Пекарни { get; set; }
        public string Название { get; set; }
        public string Полный_адрес { get; set; }
    
        public virtual ICollection<Cклады> Cклады { get; set; }
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
    }
}
