//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        public Поставщики()
        {
            this.Журнал_учета_сырья = new HashSet<Журнал_учета_сырья>();
        }
    
        public System.Guid ID_Поставщика { get; set; }
        public Nullable<System.Guid> ID_Контактного_лица { get; set; }
        public string ИНН { get; set; }
        public string Краткое_название { get; set; }
        public string Полное_название { get; set; }
        public string Адрес { get; set; }
        public string Рабочий_телефон { get; set; }
    
        public virtual Личности Личности { get; set; }
        public virtual ICollection<Журнал_учета_сырья> Журнал_учета_сырья { get; set; }
    }
}
