//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        public Продукция()
        {
            this.Остатки_продукции_на_складе = new HashSet<Остатки_продукции_на_складе>();
            this.Рецепты = new HashSet<Рецепты>();
            this.Состав_операций_по_продукции = new HashSet<Состав_операций_по_продукции>();
        }
    
        public System.Guid ID_Продукции { get; set; }
        public System.Guid ID_Типа_продукции { get; set; }
        public Nullable<int> Цена { get; set; }
        public string Ед__измерения { get; set; }
        public byte[] Изображение { get; set; }
        public string Название { get; set; }
    
        public virtual ICollection<Остатки_продукции_на_складе> Остатки_продукции_на_складе { get; set; }
        public virtual Справочник_типов_продукции Справочник_типов_продукции { get; set; }
        public virtual ICollection<Рецепты> Рецепты { get; set; }
        public virtual ICollection<Состав_операций_по_продукции> Состав_операций_по_продукции { get; set; }
    }
}
