//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рецепты
    {
        public Рецепты()
        {
            this.Состав_рецепта = new HashSet<Состав_рецепта>();
        }
    
        public System.Guid ID_Рецепта { get; set; }
        public System.Guid ID_Продукции { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
    
        public virtual Продукция Продукция { get; set; }
        public virtual ICollection<Состав_рецепта> Состав_рецепта { get; set; }
    }
}
