//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Состав_рецепта
    {
        public System.Guid ID_Состава_рецепта { get; set; }
        public System.Guid ID_Рецепта { get; set; }
        public System.Guid ID_Типа_сырья { get; set; }
        public string Ед__измерения { get; set; }
        public int Количество { get; set; }
    
        public virtual Рецепты Рецепты { get; set; }
        public virtual Справочник_типов_сырья Справочник_типов_сырья { get; set; }
    }
}
