//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public Сотрудники()
        {
            this.Журнал_учета_продукции = new HashSet<Журнал_учета_продукции>();
            this.Журнал_учета_сырья = new HashSet<Журнал_учета_сырья>();
        }
    
        public System.Guid ID_Сотрудника { get; set; }
        public System.Guid ID_Личности { get; set; }
        public System.Guid ID_Должности { get; set; }
        public Nullable<System.Guid> ID_Пекарни { get; set; }
        public System.DateTime Дата_заступления_на_должность { get; set; }
        public Nullable<System.DateTime> Дата_увольнения { get; set; }
    
        public virtual Личности Личности { get; set; }
        public virtual Пекарни Пекарни { get; set; }
        public virtual ICollection<Журнал_учета_продукции> Журнал_учета_продукции { get; set; }
        public virtual ICollection<Журнал_учета_сырья> Журнал_учета_сырья { get; set; }
        public virtual Справочник_должностей Справочник_должностей { get; set; }
    }
}
