//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_типов_сырья
    {
        public Справочник_типов_сырья()
        {
            this.Состав_рецепта = new HashSet<Состав_рецепта>();
            this.Сырье = new HashSet<Сырье>();
        }
    
        public System.Guid ID_Типа_сырья { get; set; }
        public string Тип_сырья { get; set; }
    
        public virtual ICollection<Состав_рецепта> Состав_рецепта { get; set; }
        public virtual ICollection<Сырье> Сырье { get; set; }
    }
}
