//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Справочник_должностей
    {
        public Справочник_должностей()
        {
            this.Сотрудники = new HashSet<Сотрудники>();
        }
    
        public System.Guid ID_Должности { get; set; }
        public string Краткое_название { get; set; }
        public string Полное_название { get; set; }
        public int Количество_мест { get; set; }
    
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
    }
}
