//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сырье
    {
        public Сырье()
        {
            this.Остатки_сырья_на_складе = new HashSet<Остатки_сырья_на_складе>();
        }
    
        public System.Guid ID_Сырья { get; set; }
        public System.Guid ID_Типа_сырья { get; set; }
        public Nullable<int> Цена { get; set; }
        public string Ед__измерения { get; set; }
        public string Название { get; set; }
    
        public virtual ICollection<Остатки_сырья_на_складе> Остатки_сырья_на_складе { get; set; }
        public virtual Справочник_типов_сырья Справочник_типов_сырья { get; set; }
    }
}
